<?xml version="1.0" encoding="UTF-8"?>
<project name="lab3" basedir="." default="build">

    <property file="project.properties"/>
    <property file="secret.properties"/>

    <path id="compile.classpath">
        <fileset dir="${lib.dir}" includes="**/*.jar"/>
    </path>

    <target name="scp" description="Перемещение собранного проекта по SCP">
        <scp file="${build.dir}/${war.file}"
             todir="${scp.username}@${scp.host}:${scp.remotedir}"
             port="${scp.port}"
             password="${scp.password}"
             trust="true"
             verbose="true"/>
    </target>

    <target name="download-deps">
        <mkdir dir="${lib.dir}/temp"/>
        <get src="https://repo1.maven.org/maven2/jakarta/platform/jakarta.jakartaee-web-api/9.0.0/jakarta.jakartaee-web-api-9.0.0.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.13.0/antlr4-runtime-4.13.0.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/primefaces/primefaces/14.0.6/primefaces-14.0.6-jakarta.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/primefaces/themes/all-themes/1.1.0/all-themes-1.1.0.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/webjars/npm/primeflex/3.3.1/primeflex-3.3.1.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/webjars/npm/primeicons/7.0.0/primeicons-7.0.0.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/hibernate/orm/hibernate-core/6.6.1.Final/hibernate-core-6.6.1.Final.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true" ignoreerrors="true"/>
        <get src="https://repo1.maven.org/maven2/org/jboss/logging/jboss-logging/3.5.3.Final/jboss-logging-3.5.3.Final.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/jakarta/persistence/jakarta.persistence-api/3.1.0/jakarta.persistence-api-3.1.0.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/hibernate/common/hibernate-commons-annotations/6.0.6.Final/hibernate-commons-annotations-6.0.6.Final.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.14.11/byte-buddy-1.14.11.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/jboss/spec/javax/transaction/jboss-transaction-api_1.3_spec/2.0.0.Final/jboss-transaction-api_1.3_spec-2.0.0.Final.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.4/postgresql-42.7.4.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.3.12/logback-classic-1.3.12.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.3.12/logback-core-1.3.12.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.34/lombok-1.18.34.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.10.0/junit-jupiter-api-5.10.0.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.10.0/junit-jupiter-engine-5.10.0.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/junit/platform/junit-platform-commons/1.10.0/junit-platform-commons-1.10.0.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/junit/platform/junit-platform-engine/1.10.0/junit-platform-engine-1.10.0.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.54/jsch-0.1.54.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <get src="https://repo1.maven.org/maven2/org/apache/ant/ant-jsch/1.10.14/ant-jsch-1.10.14.jar"
             dest="${lib.dir}/temp" verbose="true" usetimestamp="true"/>
        <copy todir="${lib.dir}">
            <fileset dir="${lib.dir}/temp"/>
        </copy>
        <delete dir="${lib.dir}/temp"/>
    </target>

    <target name="compile">
        <mkdir dir="${classes.dir}"/>
        <javac srcdir="${src.dir}"
               destdir="${classes.dir}"
               includeantruntime="false"
               source="17"
               target="17"
               encoding="UTF-8"
               debug="true"
               fork="true"
               executable="${javac.executable}">
            <classpath refid="compile.classpath"/>
            <compilerarg line="-Xlint:unchecked -parameters"/>
        </javac>
        <copy todir="${classes.dir}" preservelastmodified="true">
            <fileset dir="${resources.dir}" includes="**/*" excludes="**/*.java"/>
        </copy>

        <mkdir dir="${classes.dir}/META-INF"/>
        <manifest file="${build.dir}/META-INF/MANIFEST.MF" mode="update">
            <attribute name="Manifest-Version" value="1.0.0"/>
            <attribute name="Implementation-Version" value="1.0.0"/>
        </manifest>
    </target>

    <target name="build">
        <war destfile="${war.file}"
             webxml="${web.dir}/WEB-INF/web.xml"
             needxmlfile="false">
            <fileset dir="${web.dir}" excludes="WEB-INF/web.xml"/>
            <lib dir="${lib.dir}" excludes="**/*.properties"/>
            <classes dir="${classes.dir}" excludes="**/package-info.class"/>
            <metainf dir="${build.dir}/META-INF"/>
        </war>
        <antcall target="music"/>
    </target>

    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

    <target name="music" description="Play music when build is complete">
        <condition property="isWindows">
            <os family="windows"/>
        </condition>
        <condition property="isMac">
            <os family="mac"/>
        </condition>

        <exec executable="cmd" osfamily="windows" failonerror="false">
            <arg value="/c"/>
            <arg value="start"/>
            <arg value="/B"/>
            <arg value="${music.file}"/>
        </exec>

        <exec executable="/bin/sh" osfamily="mac" failonerror="false">
            <arg value="-c"/>
            <arg value="afplay '${music.file}' &amp;"/>
        </exec>
    </target>

    <target name="doc" description="Добавление MD5 и SHA-1, генерация javadoc">
        <checksum file="${war.file}" property="war.md5" algorithm="MD5"/>
        <checksum file="${war.file}" property="war.sha1" algorithm="SHA-1"/>
        <mkdir dir="${build.dir}/META-INF"/>
        <manifest file="${build.dir}/META-INF/MANIFEST.MF" mode="update">
            <attribute name="MD5" value="${war.md5}"/>
            <attribute name="SHA-1" value="${war.sha1}"/>
        </manifest>
        <war destfile="${war.file}" update="true">
            <metainf dir="${build.dir}/META-INF"/>
        </war>
        <mkdir dir="${build.dir}/javadoc"/>
        <javadoc destdir="${build.dir}/javadoc"
                 sourcepath="${src.dir}"
                 classpathref="compile.classpath"
                 packagenames="*"
                 use="true"
                 author="true"
                 version="true"
                 doctitle="Lab3 API">
        </javadoc>
        <jar destfile="${war.file}" update="true">
            <fileset dir="${build.dir}/javadoc"/>
        </jar>
    </target>

    <target name="start-env" description="Start environment: DB, server, deploy WAR, open web">

        <!-- 1. Запуск контейнера PostgreSQL -->
        <!--        <exec executable="docker" failonerror="true">-->
        <!--            <arg value="run"/>-->
        <!--            <arg value="&#45;&#45;rm"/>-->
        <!--            <arg value="-d"/>-->
        <!--            <arg value="&#45;&#45;name"/>-->
        <!--            <arg value="my-postgres"/>-->
        <!--            <arg value="-e"/>-->
        <!--            <arg value="POSTGRES_PASSWORD=postgres"/>-->
        <!--            <arg value="-p"/>-->
        <!--            <arg value="5432:5432"/>-->
        <!--            <arg value="postgres:15"/>-->
        <!--        </exec>-->

        <!-- 2. Запуск standalone.sh (WildFly / JBoss) -->
        <exec executable="${wildfly.home}/bin/standalone.sh" osfamily="unix" spawn="true"/>
        <exec executable="${wildfly.home}/bin/standalone.bat" osfamily="windows" spawn="true"/>

        <!-- 3. Копирование .war файла в папку deployments -->
        <copy file="${build.dir}/${war.file}"
              todir="${wildfly.home}/standalone/deployments"
              overwrite="true"/>

        <!-- 4. Открытие веб-браузера -->
        <condition property="isWindows">
            <os family="windows"/>
        </condition>
        <condition property="isMac">
            <os family="mac"/>
        </condition>

        <!-- Windows -->
        <exec executable="cmd" osfamily="windows" failonerror="false">
            <arg value="/c"/>
            <arg value="start"/>
            <arg value="http://localhost:8080/${project.context}"/>
        </exec>

        <!-- macOS -->
        <exec executable="open" osfamily="mac" failonerror="false">
            <arg value="http://localhost:8080/${project.context}"/>
        </exec>

        <!-- Linux -->
        <!--        <exec executable="xdg-open" osfamily="unix" failonerror="false">-->
        <!--            <arg value="http://localhost:8080/${project.context}"/>-->
        <!--        </exec>-->

    </target>

    <!-- test, native2ascii, history, diff, env, alt  -->

    <target name="env" description="Deploy to WildFly and run">
        <!-- POSTGRES -->
        <available property="docker.exists" file="${docker.home}"/>
        <fail unless="docker.exists" message="Docker not found at ${docker.home}"/>

        <exec executable="docker-compose" dir="${basedir}" failonerror="false">
            <arg value="down"/>
        </exec>

        <exec executable="docker-compose" dir="${basedir}" failonerror="true">
            <arg value="up"/>
            <arg value="-d"/>
        </exec>

        <exec executable="docker" dir="${basedir}" failonerror="true">
            <arg value="inspect"/>
            <arg value="-f"/>
            <arg value="{{.State.Running}}"/>
            <arg value="lab3-postgres"/>
        </exec>

        <!-- WILDFLY -->
        <available property="wildfly.exists" file="${wildfly.home}"/>
        <fail unless="wildfly.exists"
              message="WildFly not found at ${wildfly.home}. Please set correct wildfly.home in properties"/>

        <exec executable="${wildfly.home}/bin/jboss-cli.sh" osfamily="unix" failonerror="false">
            <arg value="--connect"/>
            <arg value="command=:shutdown"/>
        </exec>
        <sleep seconds="3"/>

        <copy file="${war.file}"
              tofile="${wildfly.deployment}/${project.war.context}"
              overwrite="true"/>

        <exec executable="${wildfly.home}/bin/standalone.sh" spawn="true">
            <arg value="-b"/>
            <arg value="0.0.0.0"/>
            <env key="JAVA_HOME" value="${java.home}"/>
        </exec>

        <waitfor maxwait="30" maxwaitunit="second">
            <http url="http://localhost:8080/"/>
        </waitfor>

        <exec executable="open" osfamily="mac">
            <arg value="http://localhost:8080/${project.context}"/>
        </exec>
        <exec executable="xdg-open" osfamily="unix" os="linux" failonerror="false">
            <arg value="http://localhost:8080/${project.context}"/>
        </exec>
        <exec executable="cmd" osfamily="windows" failonerror="false">
            <arg value="/c"/>
            <arg value="start"/>
            <arg value="http://localhost:8080/${project.context}"/>
        </exec>
    </target>


</project>