<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0"
            xmlns:m="http://ant.apache.org/ivy/maven">
    <info organisation="lab3" module="lab3"/>

    <configurations>
        <conf name="default"/>
        <conf name="runtime" extends="default"/>
        <conf name="provided" extends="default"/>
        <conf name="test" extends="default"/>
    </configurations>

    <dependencies>

    </dependencies>
</ivy-module>